### ISSUE TITLE
Having the app foregrounded does not show new notifications

### ISSUE THREAD

**Issue by akentosh** [puterstructions/wtfdiw-mobile#16]
This is by design but we need to handle it gracefully inside of the app.

**Comment by n8behavior** [comment]
After some more thought... is this really an issue?

**Comment by bfowle** [comment]
I think the ticket is worded kind of strange; from a UX standpoint the push plugin gets an `on::notification` callback where if you're on the app and get a notification it needs to either pop up a modal to have you vote then and there (or later), or toss a little (1) up in the toolbar of the app, or something down those lines.

**Comment by n8behavior** [comment]
My vote would be to drop this card completely, let it come back from a real user requests.

**Comment by bfowle** [comment]
Let's talk about it next meeting - I think it's necessary and is documented as a UX path one should take - in the plugin itself.

**Comment by bfowle** [comment]
Moving it back for now - until next meeting.

**Comment by akentosh** [comment]
Discussed - closing based on decision by the group. Concern is the data will be skewed.
