### ISSUE TITLE
Google IAM for app

### ISSUE THREAD

**Issue by akentosh** [puterstructions/wtfdiw-mobile#18]

**Comment by akentosh** [comment]
Adding a question label until I talk to Brett. 


brett [11:36 PM]  
installed the APK, getting google auth errors; i think we'll need to figure out how to properly do google auth creds, i think i may have just done debug ones - not release

**Comment by akentosh** [comment]
Moving back to in progress after talking with Brett. We can discuss on Tuesday.

**Comment by bfowle** [comment]
Relevant documentation:
- https://docs.ionic.io/services/auth/google-native.html#device-configuration
- https://github.com/EddyVerbruggen/cordova-plugin-googleplus

**Comment by bfowle** [comment]
Relevant issues pertaining to the `12501` error on CI built APKs:
- https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/165
- https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/5

May be related to the Google auth 'restrictions' for this particular key:
<img width="620" src="https://cloud.githubusercontent.com/assets/240658/19916510/e7ea03d4-a090-11e6-8517-3484b95b2688.png">

**Comment by ajerig** [comment]
Nate to assist with this.

**Comment by bfowle** [comment]
Closing in favor of Firebase 'auth' rules; also not doing this in CI anymore
