### ISSUE TITLE
Rate your "want"

### ISSUE THREAD

**Issue by bfowle** [puterstructions/wtfdiw-mobile#2]
Plus, minus, neutral

Ability to mark a "want" at some given time

Notification based; if we can do it entirely in toasts in locked screen

**Comment by n8behavior** [comment]
I seems 'beth has implemented something close to what we want for iOS and Android based on Katzer's cordova local notifications plugin.

https://github.com/elizabethrego/cordova-plugin-local-notifications

**Comment by bfowle** [comment]
For reference:
http://ionicframework.com/docs/v2/native/local-notifications/

**Comment by n8behavior** [comment]
This is mark as review.  How are people doing this?  I got a notification on my phone this morning but never since and there was no way to vote, just had the question.  Selecting it took my to my list without letting me vote.

**Comment by akentosh** [comment]
This has been cleaned up by Brett this evening. Tested and verified.
