### ISSUE TITLE
Setup OAuth

### ISSUE THREAD

**Issue by n8behavior** [puterstructions/wtfdiw-mobile#3]
To start we'll just enable the GitHub provider

**Comment by n8behavior** [comment]
Created an OAuth app in ClusterDucks GitHub organization
https://github.com/organizations/clusterducks/settings/applications/389562

Enable GitHub OAuth for FireBase
https://console.firebase.google.com/project/wtfdiw-b7b5d/authentication/providers

**Comment by akentosh** [comment]
Replaced by #18
