### ISSUE TITLE
Drawer broken

### ISSUE THREAD

**Issue by n8behavior** [puterstructions/wtfdiw-mobile#33]
Login, logout via menu, log back in, then the drawer is broken

**Comment by bfowle** [comment]
Latest build has a new, interesting behavior:
- Login
- Logout via menu
- Log back in -- the menu works again...
- Logout via menu, the login page redirects automatically as if signing in again

**MAGIC**
Keeping this open for more research/tinkering

**Comment by ajerig** [comment]
Tested good.
