### ISSUE TITLE
CI to build APK

### ISSUE THREAD

**Issue by akentosh** [puterstructions/wtfdiw-mobile#9]
getting a CI set up for building the latest APK (`ionic build`) and a little dash that we can click to download the latest... most of these push notification tests/geolocation need to be done on an actual device, not emulated unfortunately

**Comment by akentosh** [comment]
This can probably be done but we need to get creative for .ipa (ios). See issue #12 and #13

**Comment by n8behavior** [comment]
The docker image "works" not sure what the next steps are.  We should chat about this and next meeting

**Comment by akentosh** [comment]
Suggestions:
Travis to bintray (Nate has a solution)
DockerHub to Docker Cloud (1.5 GB image however) 
CaptainHook and a bash script

**Comment by nparry** [comment]
github --> travis --> bintray example is https://github.com/nparry/orderly4jvm

**Comment by n8behavior** [comment]
There are other comments about this work captured in commits.  In the future we'll likely have the complete conversation for an issue tied back...someday.  Until then, refer to all the commits on this branch for additional comments

- https://github.com/puterstructions/wtfdiw-mobile/tree/setup_travis

Also, you might need to dig through the Slack changelog for additional info related to that ^ branch

**Comment by n8behavior** [comment]
Nate, it seems you are using a personal token for Travis.  Any reason we could not use a deploy key? 

- https://github.com/puterstructions/wtfdiw-mobile/settings/keys

This way we could all managed it if needed.  MTC

**Comment by nparry** [comment]
From what I can tell:

* The Travis integration is set up as a webhook on the repo: https://github.com/puterstructions/wtfdiw-mobile/settings/hooks/10511737
* Having a particular user listed there seems to be by design? https://github.com/travis-ci/travis-ci/issues/1249#issuecomment-21076333
* You should still be able to control Travis settings at https://travis-ci.org/puterstructions/wtfdiw-mobile/settings or via the travis CLI (`gem install travis`) directly in the repo.

**Comment by n8behavior** [comment]
I wonder if in this case you can use name or organization synonymously. Perhaps using putorstructions with a deploy hook might work? But I'm completely guessing. 

If not, we could use a service/shared account approach, but that seems bad

**Comment by nparry** [comment]
To publish the APK, I'm thinking for now just dumping the file into a S3 bucket will suffice. Bintray is cool but maybe more complicated than we need for now.

So, plan is:

* Set up a bucket for wtfdiw-mobile
* Set up some AWS credentials through IAM
* Remember how to give those credentials access to write to the bucket
* Configure travis to drop the APK into the bucket (https://docs.travis-ci.com/user/deployment/s3/)

**Comment by nparry** [comment]
The setup is as follows:

* I created a S3 bucket `wtfdiw-mobile`
* I created an IAM user `travis-ci`
* I created an IAM group `wtfdiw-mobile-artifact-upload` and added `travis-ci` to the group
* I added an inline policy on the group to allow access to the bucket:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1477879799000",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:ListBucket",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::wtfdiw-mobile",
                "arn:aws:s3:::wtfdiw-mobile/*"
            ]
        }
    ]
}
```

The access credentials for `travis-ci` were encrypted with the travis CLI tool and included in the `.travis.yml` as can be seen in #21

**Comment by nparry** [comment]
The policy above produced an error:

> Oops, It looks like you tried to write to a bucket that isn't yours or doesn't exist yet. Please create the bucket before trying to write to it.

Googling found https://github.com/travis-ci/dpl/issues/237#issuecomment-122430216 that has a few extra `Action` bits, so I'm trying that.
